import { headers } from "next/headers";

import { AdminBadge, AdminCard, PageHeader } from "../components";
import ChangePasswordForm from "./ChangePasswordForm";
import { auth } from "@/lib/auth";

export const dynamic = "force-dynamic";

export default async function SettingsPage() {
  const aiEnabled =
    process.env.TRIPZ_AI_EXTRACTION === "on" && Boolean(process.env.ANTHROPIC_API_KEY);
  const session = await auth.api.getSession({ headers: await headers() });

  return (
    <>
      <PageHeader
        title="Settings"
        body="Your account, environment, storage, and admin defaults."
      />
      <div className="grid gap-4 p-4 sm:p-6 lg:grid-cols-2">
        <AdminCard className="p-5 lg:col-span-2">
          <p className="font-mono text-xs uppercase tracking-[0.18em] text-ink/45">
            Your account
          </p>
          <p className="mt-2 text-xl font-semibold">
            {session?.user?.name ?? "Signed in"}
          </p>
          <p className="mt-2 text-sm text-ink/55">
            Username <span className="font-mono text-ink">{session?.user?.username}</span>
            {" · "}
            {session?.user?.email}. Sign in with either.
          </p>
          <ChangePasswordForm />
        </AdminCard>

        <AdminCard className="p-5">
          <p className="font-mono text-xs uppercase tracking-[0.18em] text-ink/45">Database</p>
          <p className="mt-2 text-xl font-semibold">Neon Postgres</p>
          <p className="mt-2 text-sm text-ink/55">
            Connected through `DATABASE_URL`, using the pooled endpoint.
          </p>
        </AdminCard>

        <AdminCard className="p-5">
          <p className="font-mono text-xs uppercase tracking-[0.18em] text-ink/45">
            Document storage
          </p>
          <p className="mt-2 text-xl font-semibold">Vercel Blob</p>
          <p className="mt-2 text-sm text-ink/55">
            Uploaded tickets are stored here; `booking_documents.file_url` holds the blob URL.
          </p>
        </AdminCard>

        <AdminCard className="p-5">
          <div className="flex items-center justify-between gap-3">
            <p className="font-mono text-xs uppercase tracking-[0.18em] text-ink/45">
              Automatic extraction
            </p>
            {/* `success` is not one of AdminBadge's tones (default/good/warn/
                critical), so this was resolving to undefined and rendering with no
                colour at all. */}
            <AdminBadge tone={aiEnabled ? "good" : "default"}>
              {aiEnabled ? "on" : "off"}
            </AdminBadge>
          </div>
          <p className="mt-2 text-xl font-semibold">
            {aiEnabled ? "Enabled" : "Manual entry"}
          </p>
          <p className="mt-2 text-sm text-ink/55">
            {aiEnabled
              ? "Uploaded tickets are read automatically, then held for human review."
              : "Uploaded tickets are stored and queued; booking details are typed in by the team. Set `TRIPZ_AI_EXTRACTION=on` with a valid API key to turn automatic reading back on."}
          </p>
        </AdminCard>

        <AdminCard className="p-5">
          <p className="font-mono text-xs uppercase tracking-[0.18em] text-ink/45">Margin</p>
          <p className="mt-2 text-xl font-semibold">Generated by the database</p>
          <p className="mt-2 text-sm text-ink/55">
            `bookings.margin` is a stored generated column, selling price minus base cost, so it
            can never disagree with the prices behind it.
          </p>
        </AdminCard>
      </div>
    </>
  );
}
