/**
 * Margin analysis over booking rows.
 *
 * Every function below is pure and takes a plain array of booking rows, so the
 * figures can be tested against a fixture without a database. That matters here:
 * these are the numbers pricing decisions get made on, and they were derived from
 * a real export whose totals are known, so they can be asserted rather than eyeballed.
 * See `tests/margin.test.mjs`.
 *
 * Definitions, stated once:
 *   gross  - what the customer paid          (bookings.selling_price)
 *   net    - what the booking cost us        (bookings.base_cost)
 *   margin - gross minus net                 (bookings.margin, a generated column)
 *   take   - margin / gross, as a percentage
 *
 * `bookings.margin` is generated by Postgres as `selling_price - base_cost`, so it
 * cannot disagree with the prices. We still recompute when either price is present
 * and fall back to the stored value otherwise, which keeps the metrics correct for
 * rows imported before base_cost was captured.
 */

const TYPE_LABELS = {
  flight: "Flights",
  hotel: "Hotels",
  package: "Packages",
  transfer: "Transfers",
  visa: "Visa",
  insurance: "Insurance",
  other: "Other"
};

export function labelForType(type) {
  return TYPE_LABELS[type] ?? (type ? `${type[0].toUpperCase()}${type.slice(1)}` : "Unknown");
}

function num(value) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
}

export function grossOf(row) {
  return num(row.selling_price);
}

export function netOf(row) {
  return num(row.base_cost);
}

export function marginOf(row) {
  if (row.selling_price !== null && row.selling_price !== undefined && row.base_cost !== null && row.base_cost !== undefined) {
    return num(row.selling_price) - num(row.base_cost);
  }

  return num(row.margin);
}

export function takePct(gross, margin) {
  return gross > 0 ? (margin / gross) * 100 : null;
}

export function summarise(rows) {
  const gross = rows.reduce((sum, row) => sum + grossOf(row), 0);
  const net = rows.reduce((sum, row) => sum + netOf(row), 0);
  const margin = rows.reduce((sum, row) => sum + marginOf(row), 0);

  return { count: rows.length, gross, net, margin, takePct: takePct(gross, margin) };
}

/**
 * The seven figures Rao asked for, in the order he listed them.
 *
 * Verbatim, WhatsApp 2026-08-04 16:42:
 *   International booking / Domestic booking / International hotel booking /
 *   Domestic hotel booking / Total booking value / Total margin earned /
 *   Package vendor booking value / "All in numbers"
 *
 * "Booking" unqualified means a flight in his vocabulary - his ticket sheet is
 * flights - so the first two rows are flights split by market, and the next two are
 * hotels split the same way. "Package vendor" is the land/vendor sheet.
 *
 * Rows whose market was never recorded are counted in the totals but not in either
 * market split, so the four splits can legitimately sum to less than the total. That
 * is reported rather than hidden: `unclassified` says how many are missing a market.
 */
export function requestedFigures(rows) {
  const of = (type, market) =>
    rows.filter((row) => row.booking_type === type && row.market === market);

  const cut = (type, market) => {
    const group = of(type, market);
    return {
      count: group.length,
      value: group.reduce((sum, row) => sum + grossOf(row), 0),
      margin: group.reduce((sum, row) => sum + marginOf(row), 0)
    };
  };

  const packages = rows.filter((row) => row.booking_type === "package");
  const unclassified = rows.filter(
    (row) =>
      (row.booking_type === "flight" || row.booking_type === "hotel") &&
      row.market !== "domestic" &&
      row.market !== "international"
  ).length;

  return {
    internationalBooking: cut("flight", "international"),
    domesticBooking: cut("flight", "domestic"),
    internationalHotel: cut("hotel", "international"),
    domesticHotel: cut("hotel", "domestic"),
    totalBookingValue: rows.reduce((sum, row) => sum + grossOf(row), 0),
    totalMarginEarned: rows.reduce((sum, row) => sum + marginOf(row), 0),
    packageVendorValue: packages.reduce((sum, row) => sum + grossOf(row), 0),
    packageVendorCount: packages.length,
    unclassified
  };
}

/** One summary per booking_type, richest first, empty types dropped. */
export function byType(rows) {
  const groups = new Map();

  for (const row of rows) {
    const key = row.booking_type ?? "other";
    groups.set(key, [...(groups.get(key) ?? []), row]);
  }

  return [...groups.entries()]
    .map(([type, group]) => ({ type, label: labelForType(type), ...summarise(group) }))
    .sort((a, b) => b.gross - a.gross);
}

/**
 * Bookings delivered at exactly zero margin. Called out on its own because it is
 * the cut that most changes how the blended take rate should be read - a single
 * large pass-through booking can halve it.
 */
export function zeroMargin(rows) {
  const priced = rows.filter((row) => grossOf(row) > 0);
  const zero = priced.filter((row) => marginOf(row) === 0);
  const totalGross = priced.reduce((sum, row) => sum + grossOf(row), 0);
  const gross = zero.reduce((sum, row) => sum + grossOf(row), 0);

  return {
    rows: zero,
    count: zero.length,
    gross,
    shareOfGrossPct: totalGross > 0 ? (gross / totalGross) * 100 : null
  };
}

/**
 * Group by customer. A customer holding more than one booking_type is a package -
 * a whole trip sold across lines - and packages are where the blended take rate is
 * decided, so they are worth seeing as one row rather than four.
 */
export function byCustomer(rows) {
  const groups = new Map();

  for (const row of rows) {
    const key = row.customer_id ?? row.customers?.name ?? "unknown";
    groups.set(key, [...(groups.get(key) ?? []), row]);
  }

  return [...groups.entries()]
    .map(([key, group]) => ({
      key,
      name: group[0].customers?.name ?? null,
      bookings: group,
      types: [...new Set(group.map((row) => row.booking_type ?? "other"))],
      ...summarise(group)
    }))
    .sort((a, b) => b.gross - a.gross);
}
